services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-inventory
    restart: always
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
      - ./data:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=Admin!123